name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version you want to release."
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # persist-credentials: false
          fetch-depth: 0
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      # - name: Update changelog
      #   uses: stefanzweifel/changelog-updater-action@v1
      #   with:
      #     version: ${{ github.event.inputs.version }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      - name: Bump version in TOML files
        run: sh ./scriptBump.sh
      - name: Commit changelog and manifest files
        id: make-commit
        run: |

          git commit -sa -m "Prepare release ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }}

      - name: Create pull request
        run: gh pr create -B main --title "Release-v${{ github.event.inputs.version }}" --body "Yay release" --label "Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
