name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      new-version:
        type: choice
        description: "Which version you'd like to release?"
        options:
        - major
        - minor
        - patch
        - rc
        - release
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump new version in TOML files
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-edit
          version: latest
      - run: |
          OLD=$(cargo pkgid | cut -d# -f2 | cut -d: -f2)
          cargo set-version --workspace --bump ${{github.event.inputs.new-version}}    
      - name: Create release branch
        run: |
          NEW=$(cargo pkgid | cut -d# -f2 | cut -d: -f2)
          git checkout -b release/$NEW
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      - name: Updating Changelog and Dockerfile
        run: .github/scripts/Bump.sh $OLD $NEW
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check
      - name: Commit changelog and manifest files
        id: make-commit
        run: |

          git commit -sa -m "Prepare release $NEW"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin release/$NEW

      - name: Create pull request
        run: |
          echo "RELEASE_VERSION=$NEW" >> $GITHUB_ENV
          gh pr create -B main --title "Release-v$NEW" --body "Yay release" --label "Release"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      # - name: Invoke workflow in tremor-www
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: Draft new release
      #     repo: tremor-rs/tremor-www
      #     token: ${{ secrets.PAT_TOKEN }}
      #     inputs: '{ "new-version": "${{ env.RELEASE_VERSION }}"}'
      # - name: Invoke workflow in tremor-language-server
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: Draft new release
      #     repo: tremor-rs/tremor-language-server
      #     token: ${{ secrets.PAT_TOKEN }}
      #     inputs: '{ "new-version": "${{ env.RELEASE_VERSION }}"}'
