name: "Publish crates"

on: workflow_dispatch 

jobs:
  publish-crates:
    name: "Publish crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Publish tremor-common to crates.io
        uses: katyo/publish-crates@v1
        with:
          path: './tremor-common'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish tremor-value to crates.io
        uses: katyo/publish-crates@v1
        with:
          path: './tremor-value'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish tremor-influx to crates.io
        uses: katyo/publish-crates@v1
        with:
          path: './tremor-influx'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish tremor-script to crates.io
        run: |
          cd tremor-script
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}