name: "Publish new release"

on:
  pull_request:
    branches:
      - main
    types:
      - closed
      - labeled
jobs:
  release:
    name: Publish new release
    runs-on: ubuntu-latest
    if: |
       github.event.pull_request.merged == true &&
       (github.event.label.name == 'Release')
    steps:
      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Generate tags
        run: |
          git checkout main
          git pull
          git tag -a -m"Release v${new}" "v${new}"
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
