name: "Publish crates"

on: workflow_dispatch 

jobs:
  publish-tremor-common:
    name: Publish tremor common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Publish tremor-common to crates.io
        uses: katyo/publish-crates@v1
        with:
          path: './tremor-common'
          args: --no-verify
          dry-run: true

  publish-tremor-value:
    name: Publish tremor value
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Publish tremor-value to crates.io
        uses: katyo/publish-crates@v1
        with:
          path: './tremor-value'
          args: --no-verify
          dry-run: true

  publish-tremor-influx:
      name: Publish tremor influx
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
        - name: Publish tremor-value to crates.io
          uses: katyo/publish-crates@v1
          with:
            path: './tremor-value'
            args: --no-verify
            dry-run: true 

  publish-tremor-script:
      name: Publish tremor influx
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
        - name: Publish tremor-script to crates.io
          uses: Wandalen/wretry.action@v1.0.11
          with:
          action: katyo/publish-crates@v1
          with: |
            path: './tremor-script'
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          attempt_limit: 6
          attempt_delay: 10000