name: "Publish crates"

on: workflow_dispatch 

jobs:
  publish-tremor-common:
    name: Publish tremor common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Publish tremor-common to crates.io
        uses: katyo/publish-crates@v1
        with:
          path: './tremor-common'
          args: --no-verify
          dry-run: true

  publish-tremor-values:
    name: Publish tremor common
    runs-on: ubuntu-latest
    steps:
      - name: Publish tremor-value to crates.io
        uses: katyo/publish-crates@v1
        with:
          path: './tremor-value'
          args: --no-verify
          dry-run: true 
