# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]		
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ReleasePR:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Pull Request for every new push
        run: gh pr create -B main --title "Release-v${new}" --body "Yay release"
	env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

