name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and upload
        run: |
          # First, build some files to `dist/*`. Then:
          gh release create "${GITHUB_REF#refs/tags/}" dist/*.tgz dist/*.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
